### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by PeiZhangOSU** [PeiZhangOSU/TV_Tropes_Exploratory#1]
**Week 1 Goals:** 

1. Straighten up code, discard unnecessary junk bits;
2. Make it Python 2 compatible, since this project need to be moved to Python 2 remote machine;
3. Use appropriate data structures and libraries for new aims of analysis;
4. Good coding practice: functions rather than walls of code, doc string, comments, git commit comments, etc.

**TO-DO for this stage:**

- [x] Remake dataframes. Maybe switch to SQL? More flexible for other analysis later
- [X] Making repeated codes into functions
- [x] **OBSOLETE** Switch from ImdbPie to IMDbPY ([github](https://github.com/alberanid/imdbpy), [doc](http://imdbpy.sourceforge.net/support.html#documentation))
- [x] **OBSOLETE** : Switch to IMDB5000 database
- [x] **NEW ISSUE**: Switch to Bokeh sample database movies.db
- [x] Use Seaborn layout for plotting
- [x] Make new plots: popular tropes for each genre
- [x] Make new plots: popular tropes for each decade
- [x] Discard obsolete plots
- [x] Make sure whether package unidecode is still needed
